ingress:
  allow-ssh:
    source_ranges:
      - 35.235.240.0/20
    targets: ["allow-ssh"]
    rules:
      - protocol: tcp
        ports:
          - 22
egress:
  allow-all-outbound:
    targets: ["allow-all-outbound"]
